jobs:

  aborting:

    name: Abort and Retry Demo
    description: |
      This job is used for testing the 'abort and retry' feature.
      It doesn't do much on its own.

    context:

      task_defaults:
        exclusive_global_resources:
          any: true
        traits:
          Bash: true
        scripts:
          main:
            body: sleep 10
          clean-up:
            body: sleep 5
            ignore_abort: true
            start_when:
              - script: main
                states: [aborted, passed, failed, skipped]

      tasks:
        t1: {}
        t2: {}

